# Generated by Django 4.0.6 on 2022-07-18 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Familiares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familiar',
            name='fecha_nacimiento',
            field=models.CharField(max_length=40),
        ),
    ]
